In [55]:
import numpy as np

In [56]:
arr = np.linspace(1, 10, 10, dtype = 'int8')
print(arr)
bigNums = np.array([i for i in arr if ((i > 5) & (i < 9))])
print(bigNums)

[ 1  2  3  4  5  6  7  8  9 10]
[6 7 8]


In [57]:
indices_cond = arr > 2
bigNums2 = arr[arr > 2]
bigNums2[:] += 1
print(bigNums2)
print(arr)

[ 4  5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10]


In [58]:
arr[arr > 5] = 99
print(arr)

[ 1  2  3  4  5 99 99 99 99 99]


# np.where()

In [59]:
matrix = np.random.randint(0, 100, (5, 5))
print(matrix)
matrix = np.where(matrix > 50, 1, 0)
print(matrix)

[[ 3 31 96 83 38]
 [73 74 47  0 54]
 [74  5 67 98 14]
 [67 42 49 27  7]
 [ 4 38 72 36 98]]
[[0 0 1 1 0]
 [1 1 0 0 1]
 [1 0 1 1 0]
 [1 0 0 0 0]
 [0 0 1 0 1]]
