In [28]:
import numpy as np

# Numpy passes values by reference. Be careful.

In [29]:
originalArr = np.arange(0, 11)
print(originalArr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [30]:
sliceOfOriginal = originalArr[0:5]
print(sliceOfOriginal)

[0 1 2 3 4]


In [31]:
sliceOfOriginal[:] = 0 
print(sliceOfOriginal)
print(originalArr)

[0 0 0 0 0]
[ 0  0  0  0  0  5  6  7  8  9 10]


In [32]:
arrCopy = originalArr.copy()[5: 8]
print(arrCopy)

[5 6 7]


In [33]:
arrCopy[:] = 0
print(arrCopy)
print(originalArr)

[0 0 0]
[ 0  0  0  0  0  5  6  7  8  9 10]
