In [1]:
import numpy as np
import pandas as pd

# dtype

In [2]:
arr = np.array([i for i in range(10)])
print('arr:', arr)
print('arr.dtype:', arr.dtype)
print('---')
floatArr = np.array([i for i in range(10)], dtype = 'float64')
print('floatArr:', floatArr)
print('floatArr.dtype:', floatArr.dtype)
print('---')
arr = arr.astype(np.float64)
print('arr:', arr)
print('arr.dtype:', arr.dtype)
print('---')
arr = arr.astype(np.bool_)
print('arr:', arr)
print('arr.dtype:', arr.dtype)

arr: [0 1 2 3 4 5 6 7 8 9]
arr.dtype: int64
---
floatArr: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
floatArr.dtype: float64
---
arr: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
arr.dtype: float64
---
arr: [False  True  True  True  True  True  True  True  True  True]
arr.dtype: bool


# ndim

In [3]:
import numpy as np

In [4]:
scalar = np.array(22)
print('scalar: \t', scalar)
print('scalar.ndim: \t', scalar.ndim)

matrix = np.array([[1, 3, 5], [4, 8, 7]])
print('matrix:')
print(matrix)
print('matrix.ndim: \t', matrix.ndim)

scalar: 	 22
scalar.ndim: 	 0
matrix:
[[1 3 5]
 [4 8 7]]
matrix.ndim: 	 2


# Add or eliminate dimensions

In [5]:
vec = np.array([1, 2, 3], ndmin = 10)
print(vec)
print(vec.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]]
10


In [6]:
expanded = np.expand_dims( np.array([1, 2, 3]), axis = 0 )
print('expanded: ',  expanded)
print('expanded.ndim', expanded.ndim)

expanded:  [[1 2 3]]
expanded.ndim 2


In [7]:
expanded = np.expand_dims( np.array([1, 2, 3]), axis = 1 )
print('expanded: ',  expanded)
print('expanded.ndim', expanded.ndim)

expanded:  [[1]
 [2]
 [3]]
expanded.ndim 2


In [8]:
print(vec, vec.ndim)
vec2 = np.squeeze(vec)
print(vec2, vec2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


# Tensor

In [9]:
matrix1 = np.array( [ [[[[l for l in range (k * 5, (k + 1) * 5)] for k in range (h * 5, (h + 1) * 5)] 
    for h in range (i * 5, (i + 1) * 5)] for i in range (j * 5, (j + 1) * 5)] for j in range(5) ] )
print('matrix1:')
print(matrix1)
print('matrix1.ndim')
print(matrix1.ndim)


matrix1:
[[[[[   0    1    2    3    4]
    [   5    6    7    8    9]
    [  10   11   12   13   14]
    [  15   16   17   18   19]
    [  20   21   22   23   24]]

   [[  25   26   27   28   29]
    [  30   31   32   33   34]
    [  35   36   37   38   39]
    [  40   41   42   43   44]
    [  45   46   47   48   49]]

   [[  50   51   52   53   54]
    [  55   56   57   58   59]
    [  60   61   62   63   64]
    [  65   66   67   68   69]
    [  70   71   72   73   74]]

   [[  75   76   77   78   79]
    [  80   81   82   83   84]
    [  85   86   87   88   89]
    [  90   91   92   93   94]
    [  95   96   97   98   99]]

   [[ 100  101  102  103  104]
    [ 105  106  107  108  109]
    [ 110  111  112  113  114]
    [ 115  116  117  118  119]
    [ 120  121  122  123  124]]]


  [[[ 125  126  127  128  129]
    [ 130  131  132  133  134]
    [ 135  136  137  138  139]
    [ 140  141  142  143  144]
    [ 145  146  147  148  149]]

   [[ 150  151  152  153  154]
    [ 155  156  