In [1]:
import numpy as np
import pandas as pd

In [2]:
lst = [i for i in range(0, 10)]
print(lst)
print(type(lst))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [3]:
npArr = np.array(lst)
print(npArr)
print(type(npArr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


## array slicing 

In [15]:
print(npArr[::3])
print(npArr[-1])
print(npArr[::-2])

[0 3 6 9]
9
[9 7 5 3 1]


In [4]:
matrix = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
print(matrix)
matrix = np.array(matrix)
print(matrix)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Matrix slicing

In [5]:
matrix[1:3,1:3]

array([[4, 5],
       [7, 8]])