In [2]:
import numpy as np
import pandas as pd

In [3]:
lst = [i for i in range(0, 10)]
print(lst)
print(type(lst))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [4]:
npArr = np.array(lst)
print(npArr)
print(type(npArr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


## array slicing 

In [5]:
print(npArr[::3])
print(npArr[-1])
print(npArr[::-2])

[0 3 6 9]
9
[9 7 5 3 1]


In [6]:
matrix = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
print(matrix)
matrix = np.array(matrix)
print(matrix)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Matrix slicing

In [7]:
matrix[1:3,1:3]

array([[4, 5],
       [7, 8]])

# Creating Numpy Arrays

In [17]:
na0 = np.array([0, 1, 2, 3])
print(na0)
print(na0.dtype)
na1 = np.arange(0, 10, 3)
print(na1)

[0 1 2 3]
int64
[0 3 6 9]


## np.zeros; np.ones

In [21]:
zArr0 = np.zeros(4)
print(zArr0)

[0. 0. 0. 0.]


In [24]:
zMatrix0 = np.zeros(shape = (5, 5))
print(zMatrix0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
oTensor0 = np.ones(shape = (3, 3, 4))
print(oTensor0)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [30]:
spacedArr = np.linspace(0, 10, 10)
print(spacedArr)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


# Identity matrix: np.eye

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.random

In [37]:
r = np.random.rand()
print(r)
randArr = np.random.rand(4)
print(randArr)
randMatrix = np.random.rand(5, 3)
print(randMatrix)

0.42015738876639586
[0.27547947 0.77017803 0.12579128 0.24187899]
[[0.84796871 0.05186111 0.00238809]
 [0.59212516 0.70635646 0.34676756]
 [0.277728   0.1890824  0.53037156]
 [0.41652223 0.43463532 0.90622086]
 [0.18809441 0.06260121 0.57247758]]


In [55]:
#Random integer in [0, 9]
print(np.random.randint(10))

9


In [56]:
np.random.randint(1, 100, (10, 10))

array([[51, 28, 60, 45, 15,  8, 18, 56, 20, 63],
       [94, 19, 27, 88, 18, 38, 62, 34, 19, 24],
       [37, 24, 72, 36, 34, 62, 12, 58, 22, 22],
       [59, 44, 84,  5, 59, 73, 56, 27, 36, 38],
       [ 1, 81,  3, 29, 51, 17, 67, 82, 84, 75],
       [43, 22,  2, 84,  2, 13, 18, 81, 54, 40],
       [63, 26, 76, 82, 22, 39, 76, 87, 34,  5],
       [41, 74, 59, 24, 70, 36, 42, 15, 44, 16],
       [70,  9, 90, 88, 55, 84, 11, 64, 75, 73],
       [30, 87, 84, 24,  5,  3, 71, 38, 95, 38]])

# np.reshape

In [82]:
arr = np.random.randint(1, 10, (3, 2))
print(arr)
print('shape:', arr.shape)
print('np.reshape: C ')
reshapedArrC = arr.reshape((6, 1), order = 'C')
print(reshapedArrC)
print('np.reshape: F ')
reshapedArrF = arr.reshape((6, 1), order = 'F')
print(reshapedArrF)

[[9 2]
 [1 4]
 [7 3]]
shape: (3, 2)
np.reshape: C 
[[9]
 [2]
 [1]
 [4]
 [7]
 [3]]
np.reshape: F 
[[9]
 [1]
 [7]
 [2]
 [4]
 [3]]


# np.max(), np.ptp()

In [100]:
matrix = np.random.randint(0, 50, (2, 5))
print(matrix)
print('matrix.max(): \t', matrix.max())
print('matrix.max(0): \t', matrix.max(0))
print('matrix.max(1): \t', matrix.max(1))
print('matrix.argmax(): ', matrix.argmax())

print('\nmatrix.min()', matrix.min())
print('...')

#ptp := peak to peak
print('\nmatrix.pkp()', matrix.ptp()) 
print('\nmatrix.pkp(0)', matrix.ptp(0))
print('\nmatrix.pkp(1)', matrix.ptp(1))  

[[26 30  7  1 22]
 [ 2 16  0 27 18]]
matrix.max(): 	 30
matrix.max(0): 	 [26 30  7 27 22]
matrix.max(1): 	 [30 27]
matrix.argmax():  1

matrix.min() 0
...

matrix.pkp() 30

matrix.pkp(0) [24 14  7 26  4]

matrix.pkp(1) [29 27]


# np.percentile(), np.sort()

In [129]:
matrix = np.random.randint(0, 50, (2, 5))
print(matrix)
print(np.percentile(matrix, 0))
print(np.percentile(matrix, 50))
print(np.percentile(matrix, 100))

print('np.median(matrix):', np.median(matrix))
print('np.median(matrix, 0):', np.median(matrix, 0))
print('np.median(matrix, 1):', np.median(matrix, 1))

print('matrix.std(1):', matrix.std(1))

print('matrix.std(0) ** 2:', matrix.std(0) ** 2)
print('matrix.var(0):', matrix.var(0))

print('matrix.mean(1):', matrix.mean(1))

matrix.sort(0)
print('\nmatrix.sort(0)')
print(matrix)

[[16 39  9 23 15]
 [14 35 29  5 17]]
5.0
16.5
39.0
np.median(matrix): 16.5
np.median(matrix, 0): [15. 37. 19. 14. 16.]
np.median(matrix, 1): [16. 17.]
matrix.std(1): [10.30727898 10.73312629]
matrix.std(0) ** 2: [  1.   4. 100.  81.   1.]
matrix.var(0): [  1.   4. 100.  81.   1.]
matrix.mean(1): [20.4 20. ]

matrix.sort(0)
[[14 35  9  5 15]
 [16 39 29 23 17]]


# np.concatenate(), np.T

In [157]:
a = np.array([[1, 2], [3, 4]])
print('a:')
print(a)

b = np.array([5, 6])
print('\nb:')
print(b)

c = np.expand_dims(b, axis = 1)
print('\nnp.expand_dims(c, axis = 1): ')
print(c)
print('np.concatenate((a, c), axis = 1)')
print(np.concatenate((a, c), axis = 1))

#d = np.expand_dims(b, axis = 0)
#print('\nnp.expand_dims(d, axis = 0): ')
#print(d)
print('np.concatenate((a, c.T), axis = 0)')
print(np.concatenate((a, c.T), axis = 0))

a:
[[1 2]
 [3 4]]

b:
[5 6]

np.expand_dims(c, axis = 1): 
[[5]
 [6]]
np.concatenate((a, c), axis = 1)
[[1 2 5]
 [3 4 6]]
np.concatenate((a, c.T), axis = 0)
[[1 2]
 [3 4]
 [5 6]]
