In [1]:
import numpy as np
import pandas as pd

In [2]:
lst = [i for i in range(0, 10)]
print(lst)
print(type(lst))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [3]:
npArr = np.array(lst)
print(npArr)
print(type(npArr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


## array slicing 

In [4]:
print(npArr[::3])
print(npArr[-1])
print(npArr[::-2])

[0 3 6 9]
9
[9 7 5 3 1]


In [5]:
matrix = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
print(matrix)
matrix = np.array(matrix)
print(matrix)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Matrix slicing

In [6]:
matrix[1:3,1:3]

array([[4, 5],
       [7, 8]])

# Creating Numpy Arrays

In [7]:
na0 = np.array([0, 1, 2, 3])
print(na0)
print(na0.dtype)
na1 = np.arange(0, 10, 3)
print(na1)

[0 1 2 3]
int64
[0 3 6 9]


## np.zeros; np.ones

In [8]:
zArr0 = np.zeros(4)
print(zArr0)

[0. 0. 0. 0.]


In [9]:
zMatrix0 = np.zeros(shape = (5, 5))
print(zMatrix0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
oTensor0 = np.ones(shape = (3, 3, 4))
print(oTensor0)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [11]:
spacedArr = np.linspace(0, 10, 10)
print(spacedArr)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


# Identity matrix: np.eye

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.random

In [13]:
r = np.random.rand()
print(r)
randArr = np.random.rand(4)
print(randArr)
randMatrix = np.random.rand(5, 3)
print(randMatrix)

0.8885681482766067
[0.52546549 0.65100489 0.94175135 0.56316559]
[[0.70494528 0.26248147 0.72133981]
 [0.02798097 0.80985029 0.61759886]
 [0.34872961 0.92862423 0.08634467]
 [0.59968433 0.83171948 0.22383599]
 [0.79204883 0.39490201 0.47398377]]


In [14]:
#Random integer in [0, 9]
print(np.random.randint(10))

2


In [15]:
np.random.randint(1, 100, (10, 10))

array([[89,  9, 58, 30,  9, 84, 44, 54, 50, 12],
       [90, 17, 83, 72, 93, 52,  2, 75, 61, 48],
       [70, 76, 17, 75, 99, 63, 69, 54, 32, 67],
       [93, 65, 90, 61, 61, 86, 88, 88, 32,  7],
       [80, 90, 74, 70, 56,  4, 89, 18, 45, 14],
       [50,  4, 43,  2, 26, 58, 56, 20, 38, 91],
       [ 9, 97, 48, 98, 59, 32, 58, 63, 31, 91],
       [66, 35, 72, 79,  3, 56, 51, 83, 16, 74],
       [72, 22,  6, 93, 67, 71, 28, 63, 41, 67],
       [25, 78, 63, 78, 42, 16, 25, 40, 65, 38]])

# np.reshape

In [16]:
arr = np.random.randint(1, 10, (3, 2))
print(arr)
print('shape:', arr.shape)
print('np.reshape: C ')
reshapedArrC = arr.reshape((6, 1), order = 'C')
print(reshapedArrC)
print('np.reshape: F ')
reshapedArrF = arr.reshape((6, 1), order = 'F')
print(reshapedArrF)

[[8 3]
 [9 4]
 [9 9]]
shape: (3, 2)
np.reshape: C 
[[8]
 [3]
 [9]
 [4]
 [9]
 [9]]
np.reshape: F 
[[8]
 [9]
 [9]
 [3]
 [4]
 [9]]


# np.max(), np.ptp()

In [17]:
matrix = np.random.randint(0, 50, (2, 5))
print(matrix)
print('matrix.max(): \t', matrix.max())
print('matrix.max(0): \t', matrix.max(0))
print('matrix.max(1): \t', matrix.max(1))
print('matrix.argmax(): ', matrix.argmax())

print('\nmatrix.min()', matrix.min())
print('...')

#ptp := peak to peak
print('\nmatrix.pkp()', matrix.ptp()) 
print('\nmatrix.pkp(0)', matrix.ptp(0))
print('\nmatrix.pkp(1)', matrix.ptp(1))  

[[23 39 40 25 36]
 [ 4 30 39  4  7]]
matrix.max(): 	 40
matrix.max(0): 	 [23 39 40 25 36]
matrix.max(1): 	 [40 39]
matrix.argmax():  2

matrix.min() 4
...

matrix.pkp() 36

matrix.pkp(0) [19  9  1 21 29]

matrix.pkp(1) [17 35]


# np.percentile(), np.sort()

In [18]:
matrix = np.random.randint(0, 50, (2, 5))
print(matrix)
print(np.percentile(matrix, 0))
print(np.percentile(matrix, 50))
print(np.percentile(matrix, 100))

print('np.median(matrix):', np.median(matrix))
print('np.median(matrix, 0):', np.median(matrix, 0))
print('np.median(matrix, 1):', np.median(matrix, 1))

print('matrix.std(1):', matrix.std(1))

print('matrix.std(0) ** 2:', matrix.std(0) ** 2)
print('matrix.var(0):', matrix.var(0))

print('matrix.mean(1):', matrix.mean(1))

matrix.sort(0)
print('\nmatrix.sort(0)')
print(matrix)

[[41 22 29 30 27]
 [26 34 22  3 23]]
3.0
26.5
41.0
np.median(matrix): 26.5
np.median(matrix, 0): [33.5 28.  25.5 16.5 25. ]
np.median(matrix, 1): [29. 23.]
matrix.std(1): [ 6.24179461 10.20979921]
matrix.std(0) ** 2: [ 56.25  36.    12.25 182.25   4.  ]
matrix.var(0): [ 56.25  36.    12.25 182.25   4.  ]
matrix.mean(1): [29.8 21.6]

matrix.sort(0)
[[26 22 22  3 23]
 [41 34 29 30 27]]


# np.concatenate(), np.T

In [19]:
a = np.array([[1, 2], [3, 4]])
print('a:')
print(a)

b = np.array([5, 6])
print('\nb:')
print(b)

c = np.expand_dims(b, axis = 1)
print('\nnp.expand_dims(c, axis = 1): ')
print(c)
print('np.concatenate((a, c), axis = 1)')
print(np.concatenate((a, c), axis = 1))

#d = np.expand_dims(b, axis = 0)
#print('\nnp.expand_dims(d, axis = 0): ')
#print(d)
print('np.concatenate((a, c.T), axis = 0)')
print(np.concatenate((a, c.T), axis = 0))

a:
[[1 2]
 [3 4]]

b:
[5 6]

np.expand_dims(c, axis = 1): 
[[5]
 [6]]
np.concatenate((a, c), axis = 1)
[[1 2 5]
 [3 4 6]]
np.concatenate((a, c.T), axis = 0)
[[1 2]
 [3 4]
 [5 6]]
