In [1]:
import numpy as np

In [7]:
lst = np.array([i for i in range (10)])
print(lst)
print(lst * 2)
print(lst)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
arr = np.arange(0, 10)
print(arr)
print(1 / arr)

[0 1 2 3 4 5 6 7 8 9]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


/tmp/ipykernel_12241/930898093.py:3: RuntimeWarning: divide by zero encountered in true_divide
  print(1 / arr)


# matrix product

In [32]:
m1 = np.arange(0, 10)
print(m1)
m1 = m1.reshape((2, 5), order = 'C')
print('m1:')
print(m1)
m2 = m1.T
print('m2:')
print(m2)

[0 1 2 3 4 5 6 7 8 9]
m1:
[[0 1 2 3 4]
 [5 6 7 8 9]]
m2:
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [16]:
np.matmul(m1, m2)

array([[ 30,  80],
       [ 80, 255]])

In [17]:
#ow
m1 @ m2

array([[ 30,  80],
       [ 80, 255]])